### PR TITLE
:construction_worker: checking lerna as part of travis CI

### PR DESCRIPTION
**Pull request by dkhnn**
This should additionally trigger the CI
The info of the CI should be visible for the PR reviewer

### CODE REVIEW

**Comment by dkhnn** [comment]
The lerna part worked and triggered the right tests.
The test themselves failed on dependency,
This PR need to merge after the tests pass.

**Comment by dimkinv** [comment]
@dkhnn  I think we need to close this pull request as the next one already adds full flow for server including Lerna integration

**Comment by dimkinv** [comment]
Now I see that you worked on tests (I didn't) so let's push maybe my PR first deal with the test and then yours?

**Comment by dkhnn** [comment]
Just thinking the same thing as I went over yours.

**Pull request closed without merging**
